# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: nda_notice

on:
  schedule:
      - cron: '00 17 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run test.py
      run: |
        python main.py
      env:
        TOKEN_FOR_ACTION: ${{ secrets.TOKEN_FOR_ACTION }}
        REST_API_KEY: ${{ secrets.REST_API_KEY }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

        
